---
##########################################
# Installed Homebrew Packages
##########################################
homebrew_installed_packages:
  - btop
  - fastfetch
  - nmap
  - cowsay
  - fortune
  - lolcat
  - figlet
  - dockutil
  - ansible
  - ansible-lint

##########################################
# Installed Homebrew Casks
##########################################
homebrew_cask_apps:
  - font-blex-mono-nerd-font # IBM Plex Mono Nerd Font - charlieterm depends on this, so don't remove it if you're using that.
  - signal
  - tidal
  - pika
  - linearmouse
  - yubico-authenticator
  - yubico-yubikey-manager
  - vesktop
  - firefox
  - cursor
  - 1password
  - balenaetcher
  - telegram-desktop
  - vlc
  - obsidian
  - localsend
  - android-studio
  - android-platform-tools
  - orbstack
  - prismlauncher
  - steam

##########################################
# Installed Mac App Store Apps
##########################################
mas_installed_apps:
  - { id: 1037126344, name: "Apple Configurator 2" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 6444217677, name: "Lickable Menu Bar" }
  - { id: 1136220934, name: "Infuse" }
