---
- name: macOS Setup - chardidathing
  hosts: local

  vars_files:
    - config.yaml
    - app_config.yaml

  roles:
    - role: geerlingguy.mac.mas
      when: configure_mas
    - role: geerlingguy.mac.homebrew
      when: configure_brew
    - role: geerlingguy.mac.dock
      when: configure_dock

  tasks:
    - name: Kill Dock after configuration
      ansible.builtin.command: killall Dock
    - name: Configure Terminal
      ansible.builtin.include_tasks: tasks/terminal.yaml
      when: configure_terminal
    - name: Configure Git
      ansible.builtin.include_tasks: tasks/git.yaml
      when: configure_git
    - name: Configure SSH
      ansible.builtin.include_tasks: tasks/ssh.yaml
      when: configure_ssh
