- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'

- name: Ensure SSH config file exists
  ansible.builtin.file:
    path: "~/.ssh/config"
    state: touch
    mode: '0600'
    modification_time: preserve
    access_time: preserve

- name: Configure SSH to use 1Password SSH agent
  ansible.builtin.blockinfile:
    path: "~/.ssh/config"
    marker: "# {mark} Reminder: Configured by Ansible - Don't manually edit this block"
    block: |
      Host *
              IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
    create: true
